# Generated by Django 3.0.7 on 2020-06-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name': 'Удобство', 'verbose_name_plural': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='hotelphoto',
            options={'ordering': ['pk'], 'verbose_name': 'Фото отеля', 'verbose_name_plural': 'Фото отелей'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['pk'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'ordering': ['pk'], 'verbose_name': 'Фото номера', 'verbose_name_plural': 'Фото номеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(blank=True, to='booking.Service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelphoto',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='booking.Amenity', verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.SmallIntegerField(default=1, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
