# Generated by Django 3.0.7 on 2020-06-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_hotel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='owner',
        ),
        migrations.CreateModel(
            name='HotelAdminRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel', verbose_name='Отель')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hoteladminrelation',
            constraint=models.UniqueConstraint(fields=('admin', 'hotel'), name='unique admin and hotel'),
        ),
    ]
