# Generated by Django 3.0.7 on 2020-06-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200624_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphoto',
            name='hotel',
        ),
    ]
