# Generated by Django 3.0.7 on 2020-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_roomphoto_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteladminrelation',
            options={'verbose_name': 'Администратор отеля', 'verbose_name_plural': 'Администраторы отелей'},
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
