# Generated by Django 3.0.7 on 2020-06-29 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_auto_20200629_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HotelAdminRelation',
        ),
    ]
