# Generated by Django 3.0.7 on 2020-07-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20200630_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='booking.Room', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Стоимость номера',
                'verbose_name_plural': 'Стоимость номеров',
                'ordering': ['date'],
            },
        ),
    ]
