version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hotels_booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:6-alpine
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A hotels_booking worker -B
    links:
      - redis
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume: