version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hotels_booking
      - POSTGRES_PASSWORD=hotels_booking
      - POSTGRES_DB=hotels_booking_dev
  redis:
    image: redis:6-alpine
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: ./app
    command: celery -A hotels_booking worker -B
    links:
      - redis
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

volumes:
  postgres_data: